language: php

php:
- "7.1"
- "7.2"
- "7.3"

before_script:
- composer install

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
- php vendor/bin/php-coveralls -v
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

